#!/bin/sh
set -e
if [ "$1" = "remove" ] && command -v glib-compile-schemas >/dev/null 2>&1; then
    rm -f "/usr/share/gnome-shell/extensions/notistack@hemoglobina.store/schemas/gschemas.compiled" || true
fi
